name: Testing on Ubuntu

on: [push,pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.1', '3.0', '2.7']
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - ruby-version: head
            os: ubuntu-latest
            experimental: true

    name: Unit testing with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run bundle install
        run: bundle install
      - name: Run the default task
        run: bundle exec rake
